# NumPy

## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [3]:
import numpy as np
np.__version__

'1.23.3'

## 배열 생성

### 리스트로 배열 만들기

![numpy](./numpy_.png)

- 1차원 배열

In [10]:
# 리스트를 배열로 바꿔주기 때문에 리스트를 넣어주면 됨.
a1 = np.array([1, 2, 3, 4, 5])
print(a1)

# type
print(type(a1))  # <class 'numpy.ndarray'> : ndarray는 n + dimension 으로 차원을 의미한다.

# shape : 배열에 대한 모양을 보여주는 속성 
print(a1.shape)  # (5,) : 5개의 원소가 있으며 ,(쉼표) 뒤에 값이 없으니 1차원 데이터임을 알 수 있다.

# 인덱싱
print(a1[0], a1[1], a1[2], a1[3], a1[4])   # 리스트와 같이 인덱스 번호로 접근이 가능하다.

# 간단한 수정 가능
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)  

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


- 2차원 배열

In [13]:
a2 = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2)

# shape
print(a2.shape) # (3, 3) : 3행→ , 3열↓

# 인덱스 [행, 열]
print(a2[0, 0], a2[1, 1], a2[2, 2])  # 1 5 9 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9
